---
image: alpine:3.15

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
    stage: test
    before_script:
        - apk add -q bash curl openjdk11 npm
        - curl -O https://download.clojure.org/install/linux-install-1.11.1.1105.sh
        - chmod +x linux-install-1.11.1.1105.sh
        - ./linux-install-1.11.1.1105.sh
    script:
        - npx shadow-cljs release app
    artifacts:
        paths:
            - public
